[package]
name = "dummy"
version = "0.1.0"
authors = ["Jack Hogan <jackhogan11@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
esp-backtrace = { version = "0.14.0", features = [
    "esp32s3",
    "exception-handler",
    "panic-handler",
    "println",
] }
esp-hal = { version = "0.20.1", features = ["esp32s3"] }
esp-println = { version = "0.11.0", features = ["esp32s3", "log"] }
log = { version = "0.4.21" }
esp-alloc = { version = "0.4.0" }
embedded-io = "0.6.1"
esp-wifi = { version = "0.8.0", features = [
    "esp32s3",
    "phy-enable-usb",
    "utils",
    "wifi",
] }
heapless = { version = "0.8.0", default-features = false }
smoltcp = { version = "0.11.0", default-features = false, features = [
    "medium-ethernet",
    "proto-dhcpv4",
    "proto-igmp",
    "proto-ipv4",
    "socket-dhcpv4",
    "socket-icmp",
    "socket-raw",
    "socket-tcp",
    "socket-udp",
] }
embassy-executor = { version = "0.6.0", features = ["task-arena-size-12288"] }
embassy-futures = "0.1.1"
# embassy-net = { version = "0.4.0", features = ["tcp", "udp", "dhcpv4"] }
embassy-sync = "0.6.0"
embassy-time = "0.3.1"
embassy-time-driver = { version = "0.1.0", optional = true }
embedded-hal = "1.0.0"
embedded-hal-02 = { version = "0.2.7", package = "embedded-hal", features = [
    "unproven",
] }
embedded-hal-async = "1.0.0"
embedded-hal-bus = "0.2.0"
embedded-io-async = "0.6.1"
embedded-storage = "0.3.1"
anyhow = { version = "1.0.87", default-features = false }
palette = { version = "0.7.6", default-features = false, features = ["libm"] }
bincode = { version = "2.0.0-rc.3", default-features = false, features = [
    "derive",
] }
[profile.dev]
# Rust debug is too slow.
# For debug builds always builds with some optimization
opt-level = "s"

[profile.release]
codegen-units = 1        # LLVM can perform better optimizations using a single thread
debug = 2
debug-assertions = false
incremental = false
lto = 'fat'
opt-level = 's'
overflow-checks = false
